###
//Check if server is online
GET http://localhost:4000/

###
//Create goal
POST http://localhost:4000/goals
Content-Type: application/json

{
  "title": "Dormir +",
  "desiredWeeklyFrequency": 7
}

###
//Get weekly pending goals (open / completed)
GET http://localhost:4000/pending-goals

###
//Complete goal
POST http://localhost:4000/complete-goal
Content-Type: application/json

{
  "goalId": "wkqyd1kezkauv9y15anxezvj"
}

###
//Get weekly summary
GET http://localhost:4000/summary